name: Build Project

on: [push]

jobs:
   build:
      name: Building Project
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [12.x]

      steps:
         - name: Checkout
           uses: actions/checkout@v2

         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v1
           with:
              node-version: ${{ matrix.node-version }}

         - name: Clear cache 1
           run: npm cache clean --force

         - name: Clear cache 2
           run: npm cache verify

         - name: Install Packages
           run: npm install

         - name: Build Project
           run: npm run start
